### ISSUE TITLE
Ingredient Selection Interface

### ISSUE THREAD

**Issue by trinitytakei** [Canny-Code/rails-new-io#111]
## Objective
Create UI for selecting ingredients during app generation

**Note: this is already somewhat built, since these ingredients are going to show up in the same UI where database etc. are - for the alpha, just poured into a 'custom' tab**

## Tasks
- [ ] Ability to assign groups
- [ ] Create selection component
- [ ] Implement checkbox interface
- [ ] Add selection preview
- [ ] Create selection persistence
- [ ] Add selection validation
- [ ] Implement clear/reset functionality
- [ ] Write tests

## Technical Details
- Use Stimulus for interactivity
- Add selection count
- Implement category grouping
- Save selection in session

## Acceptance Criteria
- Selection works smoothly
- Preview updates instantly
- Selections persist correctly
- UI is responsive
